ui: rebrand activitydetails popop
bloomwalletio/bloom pull request #1044
Opened 2023-10-10 09:42 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-10-10 15:58 UTC, Tuditi requested changes
Some changes requested. Let me know if you want my PR to be merged onto develop after this one or that we should merge it directly onto this branch.

2023-10-10 15:58 UTC, Tuditi commented on packages/shared/src/components/molecules/ActivityInformation.svelte
> +                        ? [{ key: 'smartContract', value: localize('general.transaction') }]
I think the value is wrong here, but I opened a PR that cleans this up a bit: https://github.com/bloomwalletio/bloom/pull/1052

2023-10-10 15:58 UTC, Tuditi commented on packages/shared/src/components/molecules/ActivityInformation.svelte
> +        </div>
I think this misses a w-full, because the tab titles are not aligned: 
![image](https://github.com/bloomwalletio/bloom/assets/45079109/89cf628c-4513-466b-b901-6a7e2bc125c1)

2023-10-10 15:58 UTC, Tuditi commented on packages/shared/src/components/tiles/NftTile.svelte
> +<Tile {selected} {onClick}>
Is the surface on purpose different than the token amount tile surface? It would look better if both were assigned equal spaces.

![image](https://github.com/bloomwalletio/bloom/assets/45079109/f5c8d821-95ac-4fc7-9615-e4d414613f73)

2023-10-10 15:58 UTC, Tuditi commented on packages/shared/src/components/tiles/AliasTile.svelte
> +<Tile onClick={onTileClick}>
Surface isn't set for this tile. Same as for NFT Tile.

2023-10-11 06:23 UTC, MarkNerdi commented on packages/shared/src/components/molecules/ActivityInformation.svelte
> +        </div>
currently each single tab has constant width, therefore it looks strange if the rest is just flled up with background color. something to fix in the ui kit

2023-10-11 08:51 UTC, Tuditi approved these changes
LGTM! :fire:

2023-10-11 09:12 UTC, merged