feat: walletconnect
bloomwalletio/bloom pull request #114
Opened 2023-06-26 09:37 UTC by MarkNerdi

## Summary

1. Enable `walletConnect` feature flag
2. Go to https://react-app.walletconnect.com/
3. Select "Ethereum" and click `Connect`
4. Copy on the top right the connection code
5. Go to wallet and click `Connect` and insert the code
6. Click on `personal_sign` on the webapp, bloom should open a popup

## Changelog

```
- Please write a list of changes
```

## Testing

### Instructions

> Please describe relevant instructions, configurations, etc. for testing your changes.

...

### Platforms

> Please select any platforms where your changes have been tested.

- **Desktop**
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- **Mobile**
  - [ ] iOS
  - [ ] Android
- **Web**
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Brave
  - [ ] Safari

## Checklist

> Please tick the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my changes
- [ ] I have added or modified tests, proving my changes work as intended
- [ ] I have added comments to my code for hard-to-understand areas
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2023-06-26 12:18 UTC, Tuditi requested changes
I get the following error when trying to connect:

```
Error: Non conforming namespaces. approve() namespaces chains don't satisfy required namespaces.
      Required: eip155:5
      Approved: 
    at St (index.es.js:4:1)
    at onSessionProposal (onSessionProposal.handler.ts:14:1)
    at o.<anonymous> (initializeWalletConnect.ts:23:1)
    at o.emit (index.es.js:1:1)
    at EventEmitter.onSessionProposal (index.es.js:1:1)
    at EventEmitter.emit (events.js:153:1)
    at ss.onSessionProposeRequest (index.es.js:1:1)
 ```
 This is only shown in the console. Maybe we should also add it to the error log and show a popup?

2023-06-26 12:18 UTC, Tuditi commented on packages/desktop/components/popups/InitWalletConnectPopup.svelte
> +    let wcUri: string
```suggestion
    let walletConnectUri: string
```

2023-06-26 12:18 UTC, Tuditi commented on packages/desktop/package.json
> +        "@walletconnect/web3wallet": "^1.4.0",
```suggestion
        "@walletconnect/web3wallet": "^1.8.2",
```

2023-06-26 12:18 UTC, Tuditi commented on packages/shared/lib/auxiliary/deep-link/handlers/handleDeepLink.ts
> +    const wcConnectUri = url.pathname.split('/')[1] + url.search
```suggestion
    const walletConnectUri = url.pathname.split('/')[1] + url.search
```

2023-06-26 12:18 UTC, Tuditi commented on packages/shared/lib/tests/setup.ts
> +Object.assign(global, { TextDecoder, TextEncoder })
Maybe a comment why we added a polyfill here would be helpful.

2023-06-26 12:18 UTC, Tuditi commented on packages/shared/lib/walletconnect/handlers/eth_sendTransaction.handler.ts
> +        responseCallback({ id, error: { code: 5000, message: 'Error' }, jsonrpc: '2.0' })
Seems like this error message could be improved :relaxed:

2023-06-26 12:18 UTC, Tuditi commented on packages/shared/lib/walletconnect/handlers/onSessionRequest.handler.ts
> +    // const chainId = params.chainId
Add a todo or remove the comment if we don't need it :relaxed:

2023-06-26 12:18 UTC, Tuditi commented on packages/shared/lib/walletconnect/handlers/personal_sign.handler.ts
> +    // const address = params[1]
Same in this file.

2023-06-26 12:18 UTC, Tuditi commented on packages/shared/lib/walletconnect/handlers/eth_sendTransaction.handler.ts
> +        responseCallback({ id, error: { code: 5000, message: 'Error' }, jsonrpc: '2.0' })
Additionally, we should rethink the validation. It looks similar to the other handler, so maybe we can de-duplicate this using a Decorator or by moving it to `onSessionRequest`?

2023-06-26 12:18 UTC, Tuditi commented on packages/shared/lib/walletconnect/handlers/personal_sign.handler.ts
> +            description: 'Do you wanna sign the following message: ' + message,
Use a locale here

2023-06-26 12:18 UTC, Tuditi commented on packages/shared/lib/walletconnect/handlers/personal_sign.handler.ts
> +    // sign the message
Add an issue for this.

2023-06-26 12:18 UTC, Tuditi commented on packages/shared/lib/walletconnect/utils/initializeWalletConnect.ts
> +    projectId: process.env.WALLETCONNECT_PROJECT_ID ?? '41511f9b50c46a80cdf8bd1a3532f2f9',
What does the default value represent? Is it your personal project ID?

2023-06-26 12:18 UTC, Tuditi commented on packages/shared/lib/walletconnect/stores/wallet-client.store.ts
> +export const walletClient: Writable<Web3Wallet | undefined> = writable(undefined)
Add `getWalletClient()` and use that to get the client :relaxed:

2023-06-26 13:41 UTC, MarkNerdi commented on packages/shared/lib/walletconnect/handlers/eth_sendTransaction.handler.ts
> +        responseCallback({ id, error: { code: 5000, message: 'Error' }, jsonrpc: '2.0' })
the expected form (eg. array, obj, string etc) could always be different for each event

2023-06-26 13:50 UTC, MarkNerdi commented on packages/shared/lib/walletconnect/handlers/personal_sign.handler.ts
> +    // sign the message
https://github.com/bloomwalletio/bloom/issues/122

2023-06-26 13:51 UTC, MarkNerdi commented on packages/shared/lib/walletconnect/handlers/personal_sign.handler.ts
> +            description: 'Do you wanna sign the following message: ' + message,
this currently is just for mocking. we will have a different kind of popup once we do the real implementation

2023-06-26 13:57 UTC, MarkNerdi commented on packages/shared/lib/walletconnect/utils/initializeWalletConnect.ts
> +    projectId: process.env.WALLETCONNECT_PROJECT_ID ?? '41511f9b50c46a80cdf8bd1a3532f2f9',
yes, with this we can develop on dapp connection without exposing our real enterprise project

2023-06-29 09:08 UTC, Tuditi approved these changes
LGTM! :fire:

2023-06-29 09:12 UTC, merged