feat: auto update
bloomwalletio/bloom pull request #1214
Opened 2023-10-24 19:12 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-10-24 20:14 UTC, nicole-obrien requested changes
Can we add comments for what we need to remove post launch?

2023-10-24 20:14 UTC, nicole-obrien commented on packages/desktop/webpack.config.ts
> +        'process.env.PRIVATE_REPO_ACCESS_TOKEN': JSON.stringify(process.env.PRIVATE_REPO_ACCESS_TOKEN),
is this definitely needeD?

2023-10-25 08:16 UTC, MarkNerdi commented on packages/desktop/webpack.config.ts
> +        'process.env.PRIVATE_REPO_ACCESS_TOKEN': JSON.stringify(process.env.PRIVATE_REPO_ACCESS_TOKEN),
nope its not

2023-10-25 13:51 UTC, nicole-obrien approved these changes

2023-10-25 13:54 UTC, merged