feat: update gas estimation
bloomwalletio/bloom pull request #1268
Opened 2023-10-30 15:23 UTC by Tuditi

## Summary

Updates the gas estimation to use the public API of the wasp node.
closes: #1251 

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-11-01 10:49 UTC, nicole-obrien commented on packages/desktop/views/dashboard/drawers/network-config/views/components/AddIscpChainForm.svelte
> +    function validaterpcEndpoint(): void {
Capitalisation?

2023-11-03 08:14 UTC, MarkNerdi commented on packages/shared/src/lib/core/layer-2/actions/getGasFeeForLayer1ToLayer2Transaction.ts
> +async function getGasEstimateForOnLedgerIscpCall(
what does `onLeger` in this name mean? is `getGasEstimateForIscpCall` enough?

2023-11-03 08:31 UTC, MarkNerdi requested changes
Works super, 1 small suggestion

2023-11-03 10:11 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/actions/getGasFeeForLayer1ToLayer2Transaction.ts
> +async function getGasEstimateForOnLedgerIscpCall(
It means that it estimates the gas for an transaction initiated through an L1 transaction. You could also initiate transactions by signing them and sending them directly to the wasp node.

For clarity I followed your suggestion, since we're not using the latter.

2023-11-03 10:49 UTC, MarkNerdi approved these changes

2023-11-03 10:51 UTC, merged