ui: rebrand filters
bloomwalletio/bloom pull request #1326
Opened 2023-11-06 11:11 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-11-06 15:59 UTC, maxwellmattryan commented
Some UX feedback:
- When you enable a filter, it expands with its options. I think when you disable a filter it'd be nice if it would collapse, or maybe it's options become disabled? The dropdown arrow button at the right is nice, but I'm wondering if having the entire row/tile clickable to enable it and expand it would feel better?
- When you clear, the filters become disabled but they don't collapse. I think that would be a nice detail
- Not in scope but a reset button for a filter would be kind of nice

2023-11-06 15:59 UTC, maxwellmattryan submitted a review, later dismissed
Made a comment ^

2023-11-07 08:05 UTC, Tuditi commented on packages/shared/src/lib/core/activity/utils/isVisibleActivity.ts
I get a runtime crash whenever not inputting an amount in the Amount field. The issue is an undefined `rawAmount` at l.103.

Steps to reproduce.
1. Open Filter on Activity Tab
2. Check Amount
3. Click Apply

2023-11-07 08:40 UTC, Tuditi requested changes
Requested some changes.

2023-11-07 08:40 UTC, Tuditi commented on packages/shared/src/components/molecules/filter-items/DateFilterItem.svelte
> +        if (filterUnit.selected === item.value) return
Return on separate line!

2023-11-07 08:40 UTC, Tuditi commented on packages/shared/src/components/molecules/filter-items/DateFilterItem.svelte
The state of the days/months/years is not stored upon apply/reopen. If I reopen the modal again, the field is gone, so I don't know which one I selected anymore.

Maybe it should have a default value as well, e.g. 0 days?

2023-11-07 08:40 UTC, Tuditi commented on packages/shared/src/components/molecules/filter-items/NumberFilterItem.svelte
> +            <NumberInput bind:value={filterUnit.subunit.amount} autofocus />
The runtime crash relates to the types error thrown in the `bind:value` I presume.

2023-11-07 08:40 UTC, Tuditi commented on packages/shared/src/components/molecules/filter-items/TokenFilterItem.svelte
Maybe the asset option can have a default value of `All`? 
![image](https://github.com/bloomwalletio/bloom/assets/45079109/b2636542-ab4b-482c-91e3-346f3155e856)

2023-11-07 08:40 UTC, Tuditi commented on packages/shared/src/components/molecules/filter-items/NetworkFilterItem.svelte
This could use a default value as well, since it works a bit weird now.

1. Check checkbox
2. Click Apply
3. First option of the dropdown is applied, but isn't shown in the selected input

[Screencast from 2023-11-07 09:34:07.webm](https://github.com/bloomwalletio/bloom/assets/45079109/bf85bdea-2e06-4835-ba79-986174624f75)

2023-11-07 08:40 UTC, Tuditi commented on packages/shared/src/components/molecules/filter-items/OrderFilterItem.svelte
> +    let selectedAscDesc = options.find((option) => option.value === filterUnit.selected)
```suggestion
    let selectedAscDesc = ascDescOptions.find((option) => option.value === filterUnit.selected)
```

2023-11-07 08:40 UTC, Tuditi commented on packages/shared/src/components/molecules/filter-items/OrderFilterItem.svelte
Padding is not right for the right input field:
![image](https://github.com/bloomwalletio/bloom/assets/45079109/573be1f8-578a-43cb-acb5-9c83ed588bbd)

2023-11-07 15:43 UTC, MarkNerdi commented on packages/shared/src/components/molecules/filter-items/TokenFilterItem.svelte
that would be a bigger change and out of scope of this PR

2023-11-07 15:49 UTC, MarkNerdi commented on packages/shared/src/components/molecules/filter-items/OrderFilterItem.svelte
we need other designs for this as the space is not enough for both dropdowns. But irrelevant for this PR as we dont have this filter enabled

2023-11-08 07:37 UTC, Tuditi approved these changes
LGTM! :fire:

2023-11-08 07:53 UTC, merged