fix: filter modal height after re-open
bloomwalletio/bloom pull request #1369
Opened 2023-11-09 17:13 UTC by jeeanribeiro

## Summary

closes #1364 

## Testing

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [x] Windows

### Instructions

- Open and re-open filter modal

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-11-09 18:25 UTC, maxwellmattryan commented
The filter looks like this on my screen:
![Screenshot from 2023-11-09 12-25-21](https://github.com/bloomwalletio/bloom/assets/44885822/e498c59b-2c6b-40e4-b73f-fd4777b1e2d8)

2023-11-09 18:25 UTC, maxwellmattryan submitted a review, later dismissed
See previous comment ^

2023-11-10 07:59 UTC, MarkNerdi requested changes
Most of the time the `Filter` button needs to be pressed multiple times until the modal opens

2023-11-10 14:32 UTC, MarkNerdi approved these changes

2023-11-10 14:34 UTC, merged