Feat: Download ERC-721 content
bloomwalletio/bloom pull request #1596
Opened 2023-12-11 20:59 UTC by Tuditi

## Summary

Download ERC-721 content so it can be shown as well.
closes: #1583 

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-12-11 22:32 UTC, maxwellmattryan requested changes
One small change :pray:

2023-12-11 22:32 UTC, maxwellmattryan commented on packages/shared/src/lib/core/nfts/utils/buildNftFromPersistedErc721Nft.ts
> +            type: 'image/png',
Should use a `MimeType` enum for this?

2023-12-11 22:45 UTC, maxwellmattryan approved these changes, later dismissed
Approving - functionality is working well :+1: nice job

2023-12-12 14:04 UTC, Tuditi commented on packages/shared/src/lib/core/nfts/utils/buildNftFromPersistedErc721Nft.ts
> +            type: 'image/png',
Yup, I cleaned this part up a bit.

2023-12-12 15:04 UTC, maxwellmattryan submitted a review, later dismissed
LGTM :cherry_blossom:

2023-12-12 15:33 UTC, maxwellmattryan approved these changes

2023-12-12 15:33 UTC, merged