fix: fix ordering of logic for checking persisting and loading erc721 nfts
bloomwalletio/bloom pull request #1620
Opened 2023-12-15 16:04 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-12-17 14:54 UTC, Tuditi requested changes
Left a small request for change. Otherwise works excellent! :muscle:

2023-12-17 14:54 UTC, Tuditi commented on packages/shared/src/lib/core/nfts/actions/addOrUpdateNftInAllAccountNfts.ts
> +            }
This logic has been duplicated in the function above. This function has a confusing name as well. Maybe `addOrUpdateAllAccountNfts` would do the job?

2023-12-18 15:15 UTC, nicole-obrien commented on packages/shared/src/lib/core/nfts/actions/addOrUpdateNftInAllAccountNfts.ts
> +export function addOrUpdateAllAccountNfts(...newNfts: INft[]): void {
updateAllAccountNfts for this one

updateAllAccountNftsForAccount for the one above

2024-01-04 14:06 UTC, Tuditi submitted a review, later dismissed
Works for me, nice job! :muscle:

2024-01-04 15:39 UTC, Tuditi approved these changes
LGTM!

2024-01-04 15:41 UTC, merged