refactor: electron to typescript
bloomwalletio/bloom pull request #179
Opened 2023-06-29 01:01 UTC by jeeanribeiro

## Summary

closes #165 

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-06 21:38 UTC, maxwellmattryan submitted a review, later dismissed
LGTM :cherry_blossom:

2023-07-07 13:32 UTC, Tuditi requested changes
I cannot create a new profile (error 1)/enter a pin due to the following errors on a fresh build:
I think the methods of the PincodeManager have to be bound across the context bridge as well.
Error 1:
```
core_app__WEBPACK_IMPORTED_MODULE_1__.Platform.PincodeManager.set is not a function
    at initialisePincodeManager.ts:11:1
    at Generator.next (<anonymous>)
    at initialiseOnboardingProfile.ts:28:1
    at new Promise (<anonymous>)
    at __async (initialiseOnboardingProfile.ts:28:1)
    at initialisePincodeManager (initialisePincodeManager.ts:10:1)
    at handleSetPin (EnterPinView.svelte:33:1)
    at HTMLFormElement.onSetPinClick (EnterPinView.svelte:46:1)
    at HTMLFormElement.<anonymous> (index.mjs:432:1)
```

Error 2:
```
TypeError: _core_app__WEBPACK_IMPORTED_MODULE_3__.Platform.PincodeManager.verify is not a function
    at onSubmit (EnterPinView.svelte:95:1)
    at $$self.$$.update (EnterPinView.svelte:49:1)
    at update (index.mjs:1294:1)
    at flush (index.mjs:1258:1)
```

2023-07-07 14:06 UTC, maxwellmattryan commented
@Tuditi Did you pull in the latest changes when you had those errors?

2023-07-08 12:43 UTC, Tuditi commented on packages/desktop/lib/electron/managers/keychain.manager.ts
> +    }
We can remove this, since we're never emitting e `get-all` event.

2023-07-08 12:44 UTC, Tuditi requested changes
Yup, I forgot to pull. Everything seems to work now. One minor thing to be changed.

2023-07-09 15:27 UTC, maxwellmattryan submitted a review, later dismissed
LGTM :cherry_blossom:

2023-07-10 07:47 UTC, Tuditi approved these changes
I removed the 'getAll' event handler myself :relaxed: . LGTM!

2023-07-10 13:50 UTC, merged