feat: update electron-builder
bloomwalletio/bloom pull request #207
Opened 2023-07-05 13:21 UTC by Tuditi

## Summary

Updates the Firefly name in the electron builder package.

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-05 22:29 UTC, maxwellmattryan requested changes

2023-07-05 22:29 UTC, maxwellmattryan commented on packages/desktop/electron-builder-config.js
> +            Comment: 'Web3 wallet for IOTA/Shimmer eco-system',
ecosystem?

2023-07-05 22:29 UTC, maxwellmattryan submitted a review, later dismissed

2023-07-06 13:21 UTC, amadeu2 approved these changes

2023-07-06 13:21 UTC, merged