chore: improve amount input
bloomwalletio/bloom pull request #2300
Opened 2024-04-10 13:48 UTC by Tuditi

## Summary

Closes: https://github.com/bloomwalletio/bloom/issues/2299

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-04-12 18:30 UTC, MarkNerdi requested changes

2024-04-12 18:30 UTC, MarkNerdi commented on packages/shared/src/components/inputs/TokenAmountWithSliderInput.svelte
I cannot manually input numbers into the number input. Sliding works really good and numbers are updating instantly as well :+1:

2024-04-12 18:30 UTC, MarkNerdi commented on packages/shared/src/components/inputs/TokenAmountInput.svelte
Doesnt work on a native token without decimal places.


Somehow I reached a state where the input feels very laggy, sometimes takes up to 2 seconds to reflect the input.
Also on continue and back click it took a lot of time to load the component.   But cannot reproduce it anymore

2024-04-12 18:30 UTC, MarkNerdi commented on packages/shared/src/components/inputs/TokenAmountInput.svelte
> +                {error ? 'border-danger' : 'focus-within:border-brand border-stroke dark:border-stroke-dark'}"
focus color isnt applied
+ previously we didnt have a border, is this border defined in some new design?

2024-04-12 18:30 UTC, MarkNerdi commented on packages/shared/src/components/inputs/TokenAmountWithSliderInput.svelte
> +    <div on:click={() => inputElement?.focus()} class="cursor-text w-full flex flex-col rounded-lg">
could you instead give it a `role="slider"` or something similar?

2024-04-12 18:30 UTC, MarkNerdi commented on packages/shared/src/components/inputs/TokenAmountInput.svelte
> +            class="flex flex-row justify-center items-end w-full
maybe `role="textBox"`?

2024-04-15 14:02 UTC, jeeanribeiro commented on packages/shared/src/components/inputs/TokenAmountInput.svelte
> +                {error ? 'border-danger' : 'focus-within:border-brand border-stroke dark:border-stroke-dark'}"
For me, it is being applied, it might need `yarn build` for Tailwind to generate the classes

2024-04-15 18:35 UTC, jeeanribeiro commented on packages/shared/src/components/inputs/TokenAmountWithSliderInput.svelte
> +    <div on:click={() => inputElement?.focus()} class="cursor-text w-full flex flex-col rounded-lg">
Removed the on:click handler it was not necessary

2024-04-15 18:37 UTC, jeeanribeiro commented on packages/shared/src/components/inputs/TokenAmountInput.svelte
> +            class="flex flex-row justify-center items-end w-full
This on:click handler is just for expanding the clickable area of input, so this interaction would not be useful for screen readers as the input would be accessible by other means

2024-04-16 14:53 UTC, MarkNerdi approved these changes
LGTM

2024-04-16 14:55 UTC, merged