fix: add input validation for adding a contact network address
bloomwalletio/bloom pull request #270
Opened 2023-07-14 14:55 UTC by maxwellmattryan

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-17 14:16 UTC, MarkNerdi commented on packages/desktop/views/dashboard/contact-book/drawers/AddNetworkAddressDrawer.svelte
> +        return !handledError
```suggestion
    function validate(): boolean {
        for (const input of [addressInput, addressNameInput, networkSelectionInput]) {
            try {
                input.validate()
            } catch (err) {
                return false
            }
        }
        return true
```

2023-07-17 14:22 UTC, MarkNerdi commented on packages/shared/src/lib/core/contact/utils/validateContactAddressName.ts
> +    const name = options?.value as string
no need for the `?`

2023-07-17 14:23 UTC, MarkNerdi commented on packages/shared/src/lib/core/contact/utils/validateContactAddressName.ts
> +        const contactAddressMap = ContactManager.getNetworkContactAddressMapForContact(contactId )?.[networkId]
```suggestion
        const contactAddressMap = ContactManager.getNetworkContactAddressMapForContact(contactId)?.[networkId]
```

2023-07-17 14:23 UTC, MarkNerdi commented on packages/shared/src/lib/core/utils/interfaces/validation-options.interface.ts
> +export interface IValidationOptions {
really nice idea about this! i think we can think about using this for each validation funktion

2023-07-17 14:35 UTC, MarkNerdi requested changes
looks good!
added some minor comments

2023-07-17 22:54 UTC, maxwellmattryan commented on packages/shared/src/lib/core/utils/interfaces/validation-options.interface.ts
> +export interface IValidationOptions {
Yeah, Nicole and I came up with the idea during a pair programming session. I think with a validation function available on the input component it makes it a lot easier to write the validation code imo. It doesn't currently support `Promise`s atm but we can fix that in the future when called for :)

2023-07-18 08:38 UTC, MarkNerdi approved these changes
LGTM

2023-07-18 08:38 UTC, merged