Chore: upgrade iota wallet
bloomwalletio/bloom pull request #278
Opened 2023-07-19 12:08 UTC by Tuditi

## Summary

Upgrades @iota/wallet to rc.41, because we need EVM Support with it.

closes: https://github.com/bloomwalletio/bloom/issues/299

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-21 11:07 UTC, Tuditi commented on patches/@iota+wallet+2.0.3-rc.40.patch
We can remove this with rc.41 or @iota/sdk, since my PR has been merged with the same changes: https://github.com/iotaledger/iota-sdk/commit/0edcaf5908c9ed31da485b99e9f0f45205e7c63f. But this is useful to not block us in the meantime.

2023-07-24 08:59 UTC, nicole-obrien commented on packages/desktop/lib/electron/apis/wallet.api.ts
> +        const round = 100
Can we store these in a constant file and specify that they are the old / values for v2

2023-07-24 14:14 UTC, maxwellmattryan requested changes
One tiny requested change :pray:

2023-07-24 14:14 UTC, maxwellmattryan commented on packages/desktop/lib/electron/constants/stronghold-v2-migration.constants.ts
We should add these to the `index.ts` file

2023-07-24 15:03 UTC, Tuditi commented on packages/desktop/lib/electron/constants/stronghold-v2-migration.constants.ts
We don't follow that convention in the electron lib. There is no `index.ts` file. I think it should go in a separate PR if required, because we need to rethink how we want imports/exports in this repo.

2023-07-24 15:28 UTC, maxwellmattryan submitted a review, later dismissed
LGTM :cherry_blossom:

2023-07-24 16:37 UTC, nicole-obrien approved these changes

2023-07-24 16:37 UTC, merged