feat: use contact name in activities
bloomwalletio/bloom pull request #280
Opened 2023-07-19 14:27 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-19 23:02 UTC, maxwellmattryan requested changes
Looking good, just a few requested changes :pray:

2023-07-19 23:02 UTC, maxwellmattryan commented on packages/shared/src/lib/core/wallet/interfaces/contact-subject.interface.ts
> +    type: 'contact'
At this point it would be good to define and extend a `IBaseSubject` interface, e.g.
```typescript
interface IContactSubject extends IBaseSubject {
    type: SubjectType.Contact,
    contact: IContact
}

interface IBaseSubject {
    type: SubjectType
}

enum SubjectType {
    Account = 'account',
    Address = 'address',
    Contact = 'contact',
}
```

2023-07-19 23:02 UTC, maxwellmattryan commented on packages/shared/src/lib/core/wallet/interfaces/contact-subject.interface.ts
> +    address: string
We shouldn't need this field since it's available from the `IContact` interface

2023-07-19 23:02 UTC, maxwellmattryan commented on packages/shared/src/lib/core/wallet/utils/getAddressFromSubject.ts
> +        return subject.address
Address could / should probably be first address within the network addresses for that specific contact, then we can avoid having to define this extra field.

2023-07-19 23:02 UTC, maxwellmattryan commented on packages/shared/src/lib/core/wallet/utils/getSubjectFromAddress.ts
> +        return { type: 'contact', contact, address }
The `contact` should have the `address` already available, we just need to pick the right one given the `networkId` now :+1:

2023-07-19 23:02 UTC, maxwellmattryan commented on packages/shared/src/lib/core/contact/classes/contact-manager.class.ts
> +        return contactId ? profile.contacts[contactId] : undefined
We could just use `return ContactManager.getContact(contactId)` here?

2023-07-19 23:02 UTC, maxwellmattryan commented on packages/shared/src/components/inputs/RecipientInput.svelte
> +            if (recipient?.type === 'address' || recipient?.type === 'contact') {
Would it make more sense to have validation per `SubjectType`? Also maybe this input should be called `SubjectInput` instead, since it theoretically could be used in more places than a transfer recipient input.

2023-07-20 07:54 UTC, nicole-obrien commented on packages/shared/src/lib/core/wallet/interfaces/contact-subject.interface.ts
> +    type: 'contact'
I don't think that would aid in anyway, if the only shared prop is type, you have to right it on each interface anyway. And the type narrowing will still work with the union type subject.

2023-07-20 07:57 UTC, nicole-obrien commented on packages/shared/src/lib/core/wallet/utils/getAddressFromSubject.ts
> +        return subject.address
I don't think that will work, we choose a contact in the send flow and then we need to know the exact address that was chosen to send those funds to. We can not just assume it was the first address.

2023-07-20 07:59 UTC, nicole-obrien commented on packages/shared/src/lib/core/wallet/interfaces/contact-subject.interface.ts
> +    address: string
See other comment, we need to store the address or an id of the address chosen in some way, and the easiest is to just store the address and use it directly. It might even be better to do the same with account subjects, so we now know which exact address we send to for a given account.

2023-07-20 15:17 UTC, MarkNerdi commented on packages/shared/src/lib/core/wallet/interfaces/contact-subject.interface.ts
> +    type: 'contact'
agree to nicole. But using the enum is nice

2023-07-20 15:19 UTC, MarkNerdi commented on packages/shared/src/lib/core/wallet/utils/getSubjectFromAddress.ts
> +        return { type: 'contact', contact, address }
Contact isnt interchangable with address, because we can have multiple addresses for a `contact`-`networkId` pair.

2023-07-20 15:21 UTC, MarkNerdi commented on packages/shared/src/components/inputs/RecipientInput.svelte
> +            if (recipient?.type === 'address' || recipient?.type === 'contact') {
agreed. But the recipientinput will be updated in a separate PR, so that pr should be responsible for that

2023-07-20 16:27 UTC, maxwellmattryan commented on packages/shared/src/lib/core/wallet/utils/getAddressFromSubject.ts
> +        return subject.address
That makes sense, but I suppose we need designs for choosing the specific address when there's multiple for a specific network for a contact.

2023-07-20 16:30 UTC, maxwellmattryan commented on packages/shared/src/lib/core/wallet/interfaces/contact-subject.interface.ts
> +    type: 'contact'
Fair enough, we can always create the base interface later should we decide to add another field.

2023-07-24 17:44 UTC, maxwellmattryan approved these changes
LGTM :cherry_blossom: 

Some food for thought:
- It might be nice to add a text link from the activity to the contact information view, good for a separate polish task though.
- Because the activities are only generated on login or on the action itself, I tried sending to an address then adding that address for a new contact. The list didn't update immediately but as expected after logging out and back in the activity showed the contact name (same behavior for the opposite when deleting a contact). Another good candidate for a UX polish task :+1:

2023-07-24 17:44 UTC, merged