ff: fix menu on proposal details
bloomwalletio/bloom pull request #288
Opened 2023-07-20 08:15 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

https://github.com/iotaledger/firefly/pull/7121
https://github.com/iotaledger/firefly/pull/7158

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-20 12:26 UTC, Tuditi requested changes
I have the feeling that we changed things here with regard to how FF did it. This is not necessarily a problem, but the original issue isn't fixed. To test register to all events on https://firefly.h.testnet.shimmer.network.

![image](https://github.com/bloomwalletio/bloom/assets/45079109/3e143ed8-8337-49dd-9872-33f7daf851d7)

Maybe in this case it's better to follow the same approach as FF did?

2023-07-20 12:26 UTC, Tuditi commented on packages/desktop/components/ProposalsDetails.svelte
> +        <ProposalsDetailsButton modalPosition={{ right: '0px', top: '34px' }} />
Missing lines of code here:
![image](https://github.com/bloomwalletio/bloom/assets/45079109/76793b5c-944f-455b-86da-da33132f4d19)

2023-07-20 12:26 UTC, Tuditi commented on packages/shared/src/components/modals/ProposalsDetailsMenu.svelte
> -</Modal>
Why did we remove this instead of ProposalsDetailsButton?

2023-07-20 14:42 UTC, MarkNerdi commented on packages/desktop/components/ProposalsDetails.svelte
> +        <ProposalsDetailsButton modalPosition={{ right: '0px', top: '34px' }} />
this outer div isnt required, so even though they added it, i removed it

2023-07-20 14:43 UTC, MarkNerdi commented on packages/shared/src/components/modals/ProposalsDetailsMenu.svelte
> -</Modal>
so we have the similar structure as with the other `ProposalDetailsButton`

<MeatBallButton />
<Modal>
   <div/>
</Modal>

2023-07-22 08:25 UTC, Tuditi submitted a review, later dismissed
LGTM! Deduplicate the ModalPosition type, since it resulted in a minor type issue. Have a look and merge if you like it. :relaxed:

2023-07-24 14:59 UTC, Tuditi approved these changes

2023-07-24 14:59 UTC, merged