feat: create function for unwrapping IRC30 tokens
bloomwalletio/bloom pull request #340
Opened 2023-07-27 17:40 UTC by maxwellmattryan

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

This PR adds a function to unwrap IRC30 (+ base token) from L2.

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-08-17 21:27 UTC, maxwellmattryan commented on packages/shared/src/lib/core/layer-2/interfaces/asset-allowance.interface.ts
> +export interface IAssetAllowance {
Maybe `IEvmAssetAllowance`?

2023-08-17 21:27 UTC, maxwellmattryan commented on packages/shared/src/lib/core/wallet/actions/unwrapStardustAsset.ts
> +export async function unwrapStardustAsset(
Potentially not a good name :sweat_smile:

2023-08-23 09:12 UTC, Tuditi requested changes
It doesn't work for me. 

Stronghold: On login I receive the stronghold password popup, but then if I insert the password a blank pop-up opens.

![image](https://github.com/bloomwalletio/bloom/assets/45079109/8aa3db74-d4b3-46ed-a416-51297f0e6447)

Ledger: I have the same blank pop-up open after connect my ledger if it was in an locked state upon login. If it was already unlocked, then I get a `No signature provided` error.

2023-08-23 09:12 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/interfaces/unwrap-asset-send-metadata.interface.ts
> +}
This is a almost a duplication of `ILayer2SmartContractCallData`. It would be good to somehow reuse that interface and get rid of the code duplication.

2023-08-23 09:12 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/utils/buildUnwrapAssetParameters.ts
> +        entrypoint: 0,
What are these values? Normally, they should correspond to the first bytes of the hash of the target contract and the smart contract function.

2023-08-23 09:12 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/types/unwrap-asset-parameter.type.ts
> +    | IUnwrapAssetSendOptions
Why is this piped? I think it's safer to correctly define the type and all it's different parameters according to https://github.com/iotaledger/wasp/blob/develop/packages/vm/core/evm/iscmagic/ISCSandbox.sol#L54

2023-08-23 09:12 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/interfaces/unwrap-asset-send-options-expiration.interface.ts
> +export interface IUnwrapAssetSendOptionsExpiration {
I think we need to make these interfaces more agnostic, since it's a general argument of the `send()` function. We just happen to use it for unwrapping the assets.

2023-08-23 09:12 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/interfaces/unwrap-asset-send-metadata.interface.ts
> +export interface IUnwrapAssetSendMetadata {
Same as above. This should be more generic as it doesn't have to do anything with unwrapping per se. It just happens we use it for unwrapping.

2023-08-23 09:12 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/interfaces/asset-allowance.interface.ts
> +export interface IAssetAllowance {
I would keep it as `ILayer2AssetAllowance`. Since it's fields are very specific to how the wasp node interprets the variables. Let me know why you changed it. :relaxed:

2023-08-23 09:12 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/interfaces/unwrap-asset-send-metadata-parameters.interface.ts
> +}
I think this interface is wrong. It should be an array of `{ key, value }`. It is also used in `getAgentBalanceParameters`, so maybe it's worth extracting it from there.

Additionally, I would also make it more generic, by dropping the `UnwrapAsset` part.

2023-08-23 09:12 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/interfaces/unwrap-asset-send-options.interface.ts
> +export interface IUnwrapAssetSendOptions {
Same as above.

2023-08-23 09:12 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/interfaces/unwrap-asset-send-options-expiration.interface.ts
> +        data: Uint8Array
You could use `IUnwrapAssetTargetAddress` here, although you should rename it.

2023-08-23 20:49 UTC, maxwellmattryan commented on packages/shared/src/lib/core/layer-2/utils/buildUnwrapAssetParameters.ts
> +        entrypoint: 0,
I am assuming `0` just to indicate no value. This was taken from the EVM toolkit

2023-08-23 20:52 UTC, maxwellmattryan commented on packages/shared/src/lib/core/layer-2/interfaces/unwrap-asset-send-metadata.interface.ts
> +}
I think we should keep it because:
- this corresponds to the SC method inputs as described by the ABI so the names of the fields and typings need to be exact otherwise the object won't be encoded correctly for transactions
- the only overlapping field is `targetContract`, nothing else

2023-08-23 21:02 UTC, maxwellmattryan commented on packages/shared/src/lib/core/layer-2/types/unwrap-asset-parameter.type.ts
> +    | IUnwrapAssetSendOptions
What do you mean piped? It's a normal union type saying that an `UnwrapAssetParameter` can be any of these types, which are listed in order per the link sent.

2023-08-28 15:50 UTC, Tuditi submitted a review, later dismissed
LGTM! :fire:

2023-08-28 15:52 UTC, Tuditi approved these changes

2023-08-28 15:55 UTC, merged