feat: persist evm transactions
bloomwalletio/bloom pull request #352
Opened 2023-07-31 08:26 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-08-01 15:01 UTC, maxwellmattryan requested changes
Two minor requested changes / questions :pray:

2023-08-01 15:01 UTC, maxwellmattryan commented on packages/shared/src/lib/core/activities/stores/persisted-transactions.store.ts
> +interface IPersistedEvmTransactions {
We may want to export this interface from its own file?

2023-08-01 15:01 UTC, maxwellmattryan commented on packages/shared/src/lib/core/activities/types/persisted-evm-transaction.interface.ts
> +import { EvmTransactionData } from '@core/layer-2'
Still best to use `@core/layer-2/interfaces`... would be good to figure out this circular dep problem since it's always lurking in the shadows.

2023-08-01 15:02 UTC, maxwellmattryan submitted a review, later dismissed
LGTM :cherry_blossom:

2023-08-03 06:26 UTC, MarkNerdi commented on packages/shared/src/lib/core/activities/stores/persisted-transactions.store.ts
> +interface IPersistedEvmTransactions {
i think we wont need it in future, because the `profileId` and `accountId` level will always be abstracted away

2023-08-03 12:48 UTC, merged