enhancement: setup walletconnect drawer
bloomwalletio/bloom pull request #394
Opened 2023-08-08 08:29 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-08-08 18:48 UTC, maxwellmattryan requested changes
Some changes requested :pray:

2023-08-08 18:48 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/connectedDapps/connected-dapps.router.ts
Not an issue with this file, but we use `kebab-case` for component directory names

2023-08-08 18:48 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/connectedDapps/connected-dapps.router.ts
> +export class ConnectedDappsDrawerRouter extends Router<ConnectedDappsDrawerRoute> {
I think there's potentially a better name than `ConnectedDapps` router since there's slightly more than just the active connections that are there. I think similar to `NetworkConfig`, `DAppConfigDrawerRouter` be better. Also we should be careful to use consistent naming for these - one of either `dApp`, `Dapp`, or `DApp` then use that everwhere. `DApp` is the technically correct one I think, so perhaps that is best?

2023-08-08 18:48 UTC, maxwellmattryan commented on packages/desktop/components/buttons/ConnectedDAppsButton.svelte
See comment about file naming for this flow / collection of drawers

2023-08-08 18:48 UTC, maxwellmattryan commented on packages/desktop/components/buttons/index.js
> +export { default as ConnectedDAppsButton } from './ConnectedDAppsButton.svelte'
Should be alphabetical order

2023-08-08 18:48 UTC, maxwellmattryan commented on packages/desktop/lib/auxiliary/drawer/enums/drawer-type.enum.ts
> +    ConnectedDapps = 'connectedDapps',
See comment about naming

2023-08-08 18:48 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/connectedDapps/ConnectedDappsRouterView.svelte
> +        $connectedDappsDrawerRouter.reset()
It might be nice to have a `destroy` method on the routers that would take care of resetting everything then also setting the store to `null`

2023-08-08 18:48 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/connectedDapps/ConnectedDappsRouterView.svelte
> +        $connectedDappsDrawerRouter.reset()
Not necessarily in the scope of this PR but just an idea, wdyt?

2023-08-08 18:51 UTC, maxwellmattryan requested changes
One more change

2023-08-08 18:51 UTC, maxwellmattryan commented on packages/shared/src/locales/en.json
> +                        "connectDapp": "Connect dApp"
In the code this should be in `actions.connectDapp`

2023-08-09 13:55 UTC, MarkNerdi commented on packages/shared/src/locales/en.json
> +                        "connectDapp": "Connect dApp"
i prefer the more domain specific grouped structure, instead of putting every text thats contain in a button into  `actions`, especially as this is quite specific and not as general as eg `Confirm`, wdyt?

2023-08-09 13:57 UTC, MarkNerdi commented on packages/desktop/views/dashboard/connectedDapps/ConnectedDappsRouterView.svelte
> +        $connectedDappsDrawerRouter.reset()
i think in this case, we can just set it to `null`, i dont see a reason why we need to reset it first

2023-08-10 09:32 UTC, nicole-obrien commented on packages/shared/src/locales/en.json
> +                        "connectDapp": "Connect dApp"
if this is the only place used then this will be fine, but it does make reuse harder. Check the designs to make sure we don't need that string anywhere else

2023-08-10 12:15 UTC, MarkNerdi commented on packages/shared/src/locales/en.json
> +                        "connectDapp": "Connect dApp"
its only used in 1 location

2023-08-10 21:19 UTC, maxwellmattryan requested changes
A few minor requested changes but overall looking good :pray:

2023-08-10 21:19 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/dApps/dapps.router.ts
A little nitpicky but this directory should be `dapps`, shouldn't have any capitalization

2023-08-10 21:19 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/dApps/drawers/DAppsListDrawer.svelte
> +    function onConnectDappClick(): void {
`onConnectDAppClick`

2023-08-10 21:19 UTC, maxwellmattryan commented on packages/shared/src/locales/en.json
> +                        "connectDapp": "Connect dApp"
Should be `connectDApp`

`PascalCase` -> `DApp` / `SomethingDApp`
`camelCase` -> `dApp` / `somethingDApp`
`kebab-case` -> `dapp` / `something-dapp`

Perhaps it would be easier if we just did either `dapp` or `Dapp` because I think these naming conventions will be hard for the whole team to maintain.

2023-08-10 21:19 UTC, maxwellmattryan commented on packages/desktop/components/buttons/ConnectedDAppsButton.svelte
To match the route and other drawer buttons, this could be called `DAppsDrawerButton`

2023-08-14 16:33 UTC, maxwellmattryan requested changes
Minor changes requested

2023-08-14 16:33 UTC, maxwellmattryan commented on packages/desktop/features/wallet.features.ts
> +        enabled: true,
Disable

2023-08-14 16:33 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/dapps/dapps-route.enum.ts
> +    List = 'list',
Change to `ConnectedDapps`

2023-08-14 16:33 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/dapps/dapps.router.ts
> +export const dappsDrawerRouter = writable<DappsDrawerRouter>(undefined)
Do we need to type-define these or `undefined`? Can we initialize with nothing?

2023-08-14 16:33 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/dapps/dapps.router.ts
> +    }
Potentially not needed as we get away with drawers using `goTo`

2023-08-14 16:33 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/dapps/drawers/DappsListDrawer.svelte
Rename file

2023-08-14 16:33 UTC, maxwellmattryan commented on packages/shared/src/locales/en.json
> +                "dApps": {
Change

2023-08-14 16:33 UTC, maxwellmattryan commented on packages/shared/src/locales/en.json
> +                    "dAppsList": {
Change

2023-08-14 16:45 UTC, maxwellmattryan approved these changes

2023-08-14 16:48 UTC, merged