feat: list connected dapps
bloomwalletio/bloom pull request #403
Opened 2023-08-08 17:09 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-08-21 10:57 UTC, nicole-obrien commented on packages/desktop/views/dashboard/drawers/dapp-config/components/DappCard.svelte
> +              data: '• ' + localize(localeKey + 'connected'),
these localise are very generic and we already have them under general?

2023-08-21 10:57 UTC, Tuditi requested changes
Looks good. The connection status with a Dapp is out of sync. 

E.g.: If I click on disconnect from the app, the status for the dapp card isn't updated. 

I think it would be good to add it in this PR, but let me know if you created a separate task for it, then I can approve this one.

2023-08-21 11:00 UTC, nicole-obrien submitted a review, later dismissed

2023-08-21 11:00 UTC, nicole-obrien commented on packages/shared/src/lib/auxiliary/wallet-connect/stores/connected-dapps.store.ts
> +export const connectedDapps: Writable<IConnectedDapp[]> = writable([])
Don't we need a persisted dapps store for each profile? And then connected dapps is only when that profile is connected. Currently I am getting all dapps across all profiles

2023-08-21 11:00 UTC, nicole-obrien commented on packages/shared/src/lib/auxiliary/wallet-connect/handlers/onSessionProposal.handler.ts
> +    void getWalletClient()
I don't mind the .then but its going against convention

2023-08-22 08:35 UTC, MarkNerdi commented on packages/shared/src/lib/auxiliary/wallet-connect/stores/connected-dapps.store.ts
> +export const connectedDapps: Writable<IConnectedDapp[]> = writable([])
https://github.com/bloomwalletio/bloom/issues/466

2023-08-23 09:49 UTC, Tuditi approved these changes

2023-08-23 09:52 UTC, merged