refactor: improve network identifiers
bloomwalletio/bloom pull request #425
Opened 2023-08-10 17:45 UTC by maxwellmattryan

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

This PR refactors the implementation of network IDs for L1 and L2.

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-08-21 10:47 UTC, nicole-obrien requested changes

2023-08-21 10:47 UTC, nicole-obrien commented on packages/desktop/components/NetworkCard.svelte
> +                <NetworkIcon networkId={SupportedNetworkId.Testnet} />
Hard coded network value?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/enums/onboarding-network-type.enum.ts
> +export enum OnboardingNetworkType {
does this need to be in onboarding context?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/types/tracked-tokens.type.ts
> +export type TrackedTokens = {
is this type in the correct place?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/constants/coin-type.constant.ts
> +    [SupportedNetworkId.Iota]: IOTA_COIN_TYPE,
errors here

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/constants/default-base-token.constant.ts
> +export const DEFAULT_BASE_TOKEN: Readonly<{ [id: NetworkId]: IBaseToken }> = {
type error

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/constants/coin-type.constant.ts
> +export const COIN_TYPE: Readonly<{ [id: NetworkId]: number }> = {
type error

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/constants/coin-type.constant.ts
should this be called DEFAULT_COIN_TYPE

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/constants/default-base-token.constant.ts
> +    [SupportedNetworkId.Iota]: DEFAULT_IOTA_BASE_TOKEN,
Add a default for everyone network id

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/constants/explorer-urls.constant.ts
>  export const EXPLORER_URLS: Readonly<{ [key in NetworkId]?: string }> = {
DEFAULT_EXPOLORER_URLS

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/constants/explorer-urls.constant.ts
> +    [SupportedNetworkId.Iota]: 'https://explorer.iota.org/mainnet',
Don't need IOTA

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/constants/faucet-urls.constant.ts
> +export const FAUCET_URLS: Readonly<{ [id: NetworkId]: string }> = {
type error

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/constants/official-node-urls.constant.ts
> +export const OFFICIAL_NODE_URLS: Readonly<{ [id: NetworkId]: string[] }> = {
fix type

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/constants/official-node-urls.constant.ts
> +    [SupportedNetworkId.Iota]: [
DEFAUL_NODE_URLS

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/constants/official-node-urls.constant.ts
>          'https://chrysalis-nodes.iota.org',
don't need iota

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/utils/checkNetworkName.ts
> +export function checkNetworkName(
validation function? not very clear

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/utils/getActiveNetworkId.ts
> +export function getActiveNetworkId(): NetworkId | undefined {
-> action

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/utils/getDisplayedNameFromNetworkId.ts
> +export function getDisplayedNameFromNetworkId(networkId: NetworkId): string {
this function shouldn't be needed because you have now introduced the name field on a network, which is set in the build persisted network function

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/utils/getEvmTransactionOptions.ts
>              chainId,
type error?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/utils/getNamespaceFromNetworkId.ts
> +export function getNamespaceFromNetworkId(networkId: NetworkId): NetworkNamespace | undefined {
do we need this with split network id?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/utils/getOfficialExplorerUrl.ts
>  export function getOfficialExplorerUrl(networkId: NetworkId): string {
eventually the explorer url should be stored on the network and we can get it from there, and only use default explorer urls when building a network

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/utils/getOfficialNodes.ts
>   * Constructs a list of the official IOTA nodes for a given network.
type error in this file?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/utils/getOnboardingNetworkNameFromNetworkId.ts
> +export function getOnboardingNetworkNameFromNetworkId(networkId: NetworkId): OnboardingNetworkType {
not sure this function is needed? can we get the data from somewhere else?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/utils/isOfficialNetwork.ts
>  export function isOfficialNetwork(networkId: NetworkId): boolean {
isSupportedNetwork?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/utils/isSupportedNetworkId.ts
> +export function isSupportedNetworkId(networkId: NetworkId): boolean {
dup0licate logic on isOfficialNe
```suggestion
export function isSupportedNetworkId(networkId: NetworkId): boolean {
```twork?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/wallet/actions/sendOutput.ts
> +        const networkId = get(network)?.getMetadata()?.id
is network the best name for this store?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/wallet/actions/send/signAndSendEvmTransaction.ts
> +            coinType: ETHEREUM_COIN_TYPE,
Should not be hard coded here, we already set the coin type on the network, so if it needs hardcoding it should be when we build that network/chain

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/token/utils/isVisibleToken.ts
> +    if (filter.network.active && filter.network.selected && token.networkId !== filter.network.selected) {
this file should be an action

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/token/actions/getAccountTokensForSelectedAccount.ts
> +    const shouldCalculateFiatPrice = getNamespaceFromNetworkId(networkId) === NetworkNamespace.Stardust
worth doing this in this PR?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
> +import { COIN_TYPE, getDefaultPersistedNetwork, OnboardingNetworkType, SupportedNetworkId } from '@core/network'
can we remove the file from check?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/layer-2/utils/signEvmTransactionWithStronghold.ts
> +    chainId: EvmChainId,
type error in file for thic param

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/layer-2/utils/getIscpTransferSmartContractData.ts
> -        const evmAddress = getSelectedAccount()?.evmAddresses?.[ETH_COIN_TYPE]
do not hard code coin type

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/layer-2/utils/estimateGasForLayer1ToLayer2Transaction.ts
> +        const evmAddress = getSelectedAccount()?.evmAddresses?.[ETHEREUM_COIN_TYPE]
Do not hard code coin type

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/layer-2/interfaces/layer2-account-balance.interface.ts
> +    [networkId: NetworkId]: {
fix type

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/layer-2/constants/default-evm-transaction-options.constant.ts
> +    common: Common.custom({ chainId: EvmChainId.ShimmerEvmTestnet }),
type error?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/core/activity/actions/generateAndStoreActivitiesForAccount.ts
> +export async function generateAndStoreActivitiesForAccount(account: IAccountState, network: NetworkId): Promise<void> {
network -> networkId

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/auxiliary/icon/constants/network-icon-svg.ts
> +    [SupportedNetworkId.Iota]: Icon.Iota,
iota not supported

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/auxiliary/icon/constants/network-icon-svg.ts
> +export const NETWORK_ICON_SVG: { [id: NetworkId]: Icon } = {
type error

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/auxiliary/wallet-connect/utils/getAllEvmAddresses.ts
> +        .map((account) => account.evmAddresses[ETHEREUM_COIN_TYPE])
don't hard code cointype

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/contexts/governance/actions/setVotingPower.ts
> +            throw new Error('Something went wrong')
localise?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/contexts/governance/actions/stopVotingForProposal.ts
> +            throw new Error('Account or network undefined')
localise?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/lib/contexts/onboarding/actions/restoreBackupFromStrongholdFile.ts
> +            throw new Error()
erorr message?

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/components/atoms/NetworkIcon.svelte
> +    const classesMap: { [id: NetworkId]: Record<string, string> } = {
type and remove iota support

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/components/molecules/TokenIcon.svelte
> +                    icon: NETWORK_ICON_SVG[baseNetworkId],
type error

2023-08-21 10:47 UTC, nicole-obrien commented on packages/shared/src/components/organisms/NodeConfigurationForm.svelte
> +            SupportedNetworkId.Iota,
remove iota

2023-08-21 10:47 UTC, nicole-obrien commented on packages/desktop/components/ContactAddressCard.svelte
> +            <NetworkIcon networkId={SupportedNetworkId.Testnet} />
hard coded network id

2023-08-21 10:47 UTC, nicole-obrien commented on packages/desktop/views/dashboard/drawers/network-config/views/components/AddIscpChainForm.svelte
> +        id: '',
type error

2023-08-21 10:47 UTC, nicole-obrien commented on packages/desktop/views/dashboard/send-flow/views/components/EvmTransactionDetails.svelte
> +                <NetworkIcon networkId={SupportedNetworkId.Testnet} height={16} width={16} outlined={false} />
hardcoded network id

2023-08-21 11:54 UTC, MarkNerdi commented on packages/desktop/views/dashboard/send-flow/views/components/EvmTransactionDetails.svelte
> +                <NetworkIcon networkId={SupportedNetworkId.Testnet} height={16} width={16} outlined={false} />
to be fixed once we have the destinationNetworkId on the sendflow params

2023-08-21 12:59 UTC, MarkNerdi commented on packages/shared/src/lib/auxiliary/wallet-connect/utils/getAllEvmAddresses.ts
> +        .map((account) => account.evmAddresses[ETHEREUM_COIN_TYPE])
will be fixed in this https://github.com/bloomwalletio/bloom/issues/461

2023-08-21 13:34 UTC, MarkNerdi commented on packages/desktop/components/ContactAddressCard.svelte
> +            <NetworkIcon networkId={SupportedNetworkId.Testnet} />
will be fixed here https://github.com/bloomwalletio/bloom/issues/463

2023-08-21 15:40 UTC, MarkNerdi commented on packages/shared/src/lib/core/network/utils/getOnboardingNetworkNameFromNetworkId.ts
> +export function getOnboardingNetworkNameFromNetworkId(networkId: NetworkId): OnboardingNetworkType {
it is needed for featureflag and translations

2023-08-21 15:50 UTC, MarkNerdi commented on packages/shared/src/lib/core/wallet/actions/sendOutput.ts
> +        const networkId = get(network)?.getMetadata()?.id
https://github.com/bloomwalletio/bloom/issues/464

2023-08-22 12:27 UTC, nicole-obrien requested changes

2023-08-22 12:27 UTC, nicole-obrien commented on packages/shared/src/lib/core/wallet/actions/mintNft.ts
>              return
Do you need to throw an error here like the others?

2023-08-22 12:27 UTC, nicole-obrien commented on packages/shared/src/lib/core/token/tests/convertToRawAmount.test.ts
>  import { IotaUnit } from '@core/utils'
unused import

2023-08-22 12:27 UTC, nicole-obrien commented on packages/shared/src/lib/core/profile-manager/utils/buildProfileManagerOptionsFromProfileData.ts
>  ): Promise<ProfileManagerOptions> {
type errors in here

2023-08-22 12:27 UTC, nicole-obrien commented on packages/shared/src/lib/core/network/actions/addDefaultNodesToClientOptions.ts
>          (officialNode) => !currentNodes.some((currentNode) => currentNode.url === officialNode.url)
type error

2023-08-22 12:27 UTC, nicole-obrien commented on packages/shared/src/lib/core/layer-2/constants/default-evm-transaction-options.constant.ts
>  export const DEFAULT_EVM_TRANSACTION_OPTIONS: TxOptions = {
unused file

2023-08-22 12:27 UTC, nicole-obrien commented on packages/shared/src/lib/contexts/governance/actions/stopVotingForProposal.ts
>  export async function stopVotingForProposal(eventId: string): Promise<Transaction> {
no return statement

2023-08-22 12:27 UTC, nicole-obrien commented on packages/desktop/components/NetworkCard.svelte
> +                {#if id}
why not pass the id in here?

2023-08-22 22:44 UTC, nicole-obrien commented on packages/shared/src/lib/core/wallet/actions/mintNft.ts
>              return
How come this is resolved if the other files all throw an error?

2023-08-22 22:51 UTC, nicole-obrien requested changes

2023-08-22 22:51 UTC, nicole-obrien commented on packages/shared/src/lib/core/wallet/tests/getOutputParameters.test.ts
> +            [SupportedNetworkId.Testnet]: {
not imported

2023-08-22 22:51 UTC, nicole-obrien commented on packages/shared/src/lib/core/activity/actions/generateAndStoreActivitiesForAllAccounts.ts
> +            throw new Error('Accounts or network not defined')
localise

2023-08-23 09:10 UTC, nicole-obrien approved these changes

2023-08-23 09:14 UTC, merged