enhancement: handle Ledger EVM transactions when blind signing is disabled
bloomwalletio/bloom pull request #434
Opened 2023-08-14 21:18 UTC by maxwellmattryan

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-08-17 19:50 UTC, MarkNerdi commented on packages/desktop/views/dashboard/send-flow/views/TransactionSummaryView.svelte
> +                await sendTransactionFromEvm(preparedTransaction, chain, () => {})
if we dont need a callback anymore, remove that param

2023-09-06 21:31 UTC, nicole-obrien requested changes

2023-09-06 21:31 UTC, nicole-obrien commented on packages/desktop/lib/electron/utils/ledger.utils.ts
> +import { IEvmTransactionSignature } from '@core/layer-2/interfaces'
duplicate imports

2023-09-06 21:31 UTC, nicole-obrien commented on packages/desktop/lib/electron/utils/ledger.utils.ts
> +        arbitraryDataEnabled: Boolean(settings.arbitraryDataEnabled),
type error

2023-09-06 21:31 UTC, nicole-obrien commented on packages/desktop/views/dashboard/Dashboard.svelte
> +            stopPollingLedgerDeviceState()
should this be in logout?

2023-09-06 21:31 UTC, nicole-obrien commented on packages/shared/src/lib/core/ledger/helpers/deconstructLedgerDeviceStatePollingConfiguration.ts
> +export function deconstructLedgerDeviceStatePollingConfiguration(
is this function overkill

2023-09-06 21:31 UTC, nicole-obrien commented on packages/shared/src/lib/core/ledger/interfaces/ledger-app-settings.interface.ts
> +export interface ILedgerEthereumAppSettings extends ILedgerAppBaseSettings {
seperate file?

2023-09-06 21:31 UTC, nicole-obrien commented on packages/shared/src/lib/core/ledger/interfaces/ledger-app-settings.interface.ts
> +interface ILedgerAppBaseSettings {
seperate file?

2023-09-06 21:31 UTC, nicole-obrien commented on packages/shared/src/lib/core/ledger/utils/buildLedgerDeviceState.ts
> +            ...(status.app?.name === LedgerAppName.Shimmer && {
type error

2023-09-06 21:31 UTC, nicole-obrien commented on packages/shared/src/lib/core/profile-manager/actions/events-handlers/handleTransactionProgressEvent.ts
>                      hideClose: true,
should be able to close it

2023-09-06 21:36 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/Dashboard.svelte
> +            stopPollingLedgerDeviceState()
Seems like it's already there too

2023-09-06 21:45 UTC, maxwellmattryan commented on packages/shared/src/lib/core/profile-manager/actions/events-handlers/handleTransactionProgressEvent.ts
>                      hideClose: true,
This has to do with the L1 flow, maybe we should test that too before making this change. Will add for L2 though :+1:

2023-09-12 21:27 UTC, nicole-obrien requested changes
Seems to work on shimmer evm now, but errors on shimmer.
- crashes when trying to send without blind signing

2023-09-13 16:04 UTC, nicole-obrien approved these changes

2023-09-13 16:07 UTC, merged