feat: connection confirmation page
bloomwalletio/bloom pull request #460
Opened 2023-08-20 19:47 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-08-24 15:31 UTC, Tuditi requested changes
Looks good, few changes requested! :muscle:

2023-08-24 15:31 UTC, Tuditi commented on packages/shared/src/lib/auxiliary/wallet-connect/actions/pairWithNewDapp.ts
> +        console.error('already connected', e)
Shouldn't this check move to the `validateConnectionCode()`? Or instead of showing it in the console, show it directly to the user?

2023-08-24 15:31 UTC, Tuditi commented on packages/desktop/views/dashboard/drawers/dapp-config/views/InputConnectionCodeDrawer.svelte
> +<DrawerTemplate title={localize('views.dashboard.drawers.dApps.inputConnectionCode.title')} {drawerRouter}>
The locale's need a rename, since we decided to go with `dapp` instead of `dApp`.

2023-08-24 15:31 UTC, Tuditi commented on packages/shared/src/lib/auxiliary/wallet-connect/utils/validateConnectionCode.ts
> +        throw Error(localize('error.deprecatedVersion'))
I think these locales are missing.

2023-08-24 15:31 UTC, Tuditi commented on packages/shared/src/lib/auxiliary/wallet-connect/utils/validateConnectionCode.ts
> +        new URL(uri)
```suggestion
    let url: URL
    try {
        url = new URL(uri)
```

2023-08-24 15:31 UTC, Tuditi commented on packages/shared/src/lib/auxiliary/wallet-connect/utils/validateConnectionCode.ts
> +    }
I'm also missing an additional validation here. If you connect to Sushiswap, it throws a namespace error which hides the button by throwing a notification over it. Not sure if it is possible to change this somehow.

![image](https://github.com/bloomwalletio/bloom/assets/45079109/f3cfaf11-3fb6-4ff1-9d4d-94fd915e997f)

2023-08-25 08:34 UTC, MarkNerdi commented on packages/shared/src/lib/auxiliary/wallet-connect/actions/pairWithNewDapp.ts
> +        console.error('already connected', e)
i think this needs some design input, as i think we'd expect a prompt to the user, if they want to reactivate the connection because their already connected. 
https://github.com/bloomwalletio/bloom/issues/470

2023-08-25 08:37 UTC, MarkNerdi commented on packages/shared/src/lib/auxiliary/wallet-connect/utils/validateConnectionCode.ts
> +    }
a few errors can only be thrown after the user tries to connect. We need to investigate if we can simulate such a connection to get the errors before hand. 
https://github.com/bloomwalletio/bloom/issues/503

2023-08-25 10:07 UTC, Tuditi approved these changes
LGTM! :fire:

2023-08-25 11:41 UTC, Tuditi approved these changes

2023-08-25 11:47 UTC, merged