feat: implement signing message popup
bloomwalletio/bloom pull request #512
Opened 2023-08-28 11:53 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-08-29 08:02 UTC, Tuditi requested changes
Some changes requested. I didn't manage to get into the happy flow.

2023-08-29 08:02 UTC, Tuditi commented on packages/shared/src/lib/core/stronghold/utils/signEvmTransactionWithStronghold.ts
>  export async function signEvmTransactionWithStronghold(
This has to be correctly imported in `signAndSendEvmTransaction`.

2023-08-29 08:02 UTC, Tuditi commented on packages/shared/src/lib/core/stronghold/utils/signMessageWithStronghold.ts
> +    signStandart: 'eth_sign' | 'personal_sign',
```suggestion
    signStandard: 'eth_sign' | 'personal_sign',
```

2023-08-29 08:02 UTC, Tuditi commented on packages/shared/src/lib/auxiliary/wallet-connect/handlers/onSessionRequest.handler.ts
> +    const chain = get(network)?.getChain(SupportedNetworkId.ShimmerEvmTestnet ?? chainId)
Use getNetwork()

2023-08-29 08:02 UTC, Tuditi commented on packages/desktop/components/popups/SignMessagePopup.svelte
> +                        />
This needs some loven on dark mode:

![image](https://github.com/bloomwalletio/bloom/assets/45079109/4418c36b-2970-43b3-930f-186b3941ab90)

2023-08-29 08:02 UTC, Tuditi commented on packages/shared/src/lib/core/stronghold/utils/getSignatureForStringWithStronghold.ts
> +    const { signature } = await account.signSecp256k1Ecdsa(text, bip44Path)
Wherever this is called, it needs to check whether the stronghold has been unlocked first.

2023-08-29 08:02 UTC, Tuditi commented on packages/shared/src/lib/core/stronghold/utils/signMessageWithStronghold.ts
> +    const signedTransaction = createSignedTransaction(transaction, signature, chainId)
`transaction` is undefined here.

2023-08-29 08:02 UTC, Tuditi commented on packages/shared/src/lib/core/stronghold/utils/signMessageWithStronghold.ts
> +    rawTx[8] = signature.s
We merged in a function that removes the leading zeros (`removeLeadingZeros()`). It should be used here, since we had some errors thrown due to that.

2023-08-29 08:02 UTC, Tuditi commented on packages/shared/src/locales/en.json
> +            "warning": "Dapp cannot be determined. No balance will be sent in the process of signing this message.",
```suggestion
            "warning": "dApp cannot be determined. No balance will be sent in the process of signing this message.",
```

2023-08-30 08:16 UTC, Tuditi requested changes
Some minor comments. Otherwise looks really good!

2023-08-30 08:16 UTC, Tuditi commented on packages/desktop/components/popups/SignMessagePopup.svelte
> +    export let _onMount: (..._: any[]) => Promise<void> = async () => {}
Are you using this prop anywhere?

2023-08-30 08:16 UTC, Tuditi commented on packages/shared/src/lib/auxiliary/wallet-connect/handlers/onSessionRequest.handler.ts
>      }
Maybe worth passing only the `message` instead of the full `JsonRpcResponse`, so that you don't have to pass around the `requestId` everywhere?

It would result in a lot less duplication if you create the response in this function.

2023-08-30 08:16 UTC, Tuditi commented on packages/desktop/components/popups/SignMessagePopup.svelte
> +    export let _onMount: (..._: any[]) => Promise<void> = async () => {}
Are you using `_onMount` anywhere?

2023-08-30 08:16 UTC, Tuditi commented on packages/shared/src/locales/en.json
> +            "title": "Sign a message",
```suggestion
            "title": "Sign a message through WalletConnect",
```

2023-08-30 08:16 UTC, Tuditi commented on packages/shared/src/locales/en.json
> +            "title": "Sign a message",
Maybe this would be a good addition? Otherwise it feels very dry :D

2023-08-30 08:20 UTC, MarkNerdi commented on packages/shared/src/locales/en.json
> +            "title": "Sign a message",
IMO the term "walletconnect" should only face the user on dapp connection. Once the connection is established, it isnt relevant anymore. Maybe "Sign message for dApp"?

2023-08-30 08:24 UTC, MarkNerdi commented on packages/desktop/components/popups/SignMessagePopup.svelte
> +    export let _onMount: (..._: any[]) => Promise<void> = async () => {}
it will be used on unlocking stronghold / ledger, because it will always close/reopen this popup

2023-08-30 08:29 UTC, Tuditi commented on packages/shared/src/locales/en.json
> +            "title": "Sign a message",
Maybe `Sign message from dApp`? But I guess `for` is better, since it puts an emphasis on where the message will arrive. I'll leave it up to you :relaxed:

2023-08-30 08:29 UTC, Tuditi commented on packages/desktop/components/popups/SignMessagePopup.svelte
> +    export let _onMount: (..._: any[]) => Promise<void> = async () => {}
duplicate

2023-08-30 09:14 UTC, Tuditi commented on packages/desktop/components/popups/SignMessagePopup.svelte
> +    export let _onMount: (..._: any[]) => Promise<void> = async () => {}
Maybe add a TODO for places where you write code for future PRs.

2023-08-30 09:56 UTC, Tuditi submitted a review, later dismissed
LGTM!

2023-08-30 11:42 UTC, Tuditi approved these changes

2023-08-30 11:46 UTC, merged