feat: integrate function for unwrapping base / IRC30 tokens
bloomwalletio/bloom pull request #519
Opened 2023-08-28 17:06 UTC by maxwellmattryan

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

This PR implements the functionality to unwrap base tokens and IRC30 tokens from L2.

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-08-30 07:42 UTC, MarkNerdi commented on packages/shared/src/lib/core/layer-2/constants/fallback-estimated-gas.constant.ts
> +    [SendFlowType.TokenUnwrap]: 54800,
is this a realistic estimation?

2023-08-30 07:44 UTC, MarkNerdi commented on packages/shared/src/lib/core/wallet/actions/send/createEvmTransactionFromSendFlowParameters.ts
> -    chain: IChain,
why remove this parameter? We need to get the chain in line 18 again

2023-08-30 08:03 UTC, MarkNerdi commented on packages/shared/src/lib/core/wallet/actions/send/createEvmChainToStardustNetworkTransaction.ts
> +}
```suggestion
    if (!recipientAddress) {
        return undefined
    }
    const { targetAddress, adjustMinimumStorageDeposit, sendMetadata, sendOptions } =
        buildUnwrapAssetParameters(recipientAddress)

    const transferredAsset = buildTransferredAssetFromSendFlowParameters(sendFlowParameters)
    if (!transferredAsset) {
        return undefined
    }
    const assetAllowance = buildAssetAllowance(
        transferredAsset,
        FALLBACK_ESTIMATED_GAS[SendFlowType.TokenUnwrap]
    )
    const contract = chain?.getContract(ContractType.IscMagic, ISC_MAGIC_CONTRACT_ADDRESS)
    const data =
       (await contract?.methods
          .send(targetAddress, assetAllowance, adjustMinimumStorageDeposit, sendMetadata, sendOptions)
           .encodeABI()) ?? ''

     const provider = chain?.getProvider() as Web3
     const originAddress = account?.evmAddresses?.[ETHEREUM_COIN_TYPE] ?? ''
        return await buildEvmTransactionData(provider, originAddress, ISC_MAGIC_CONTRACT_ADDRESS, '0', data)
}
```

2023-08-30 09:49 UTC, Tuditi requested changes
Happy flow works well for Stronghold.

With Ledger I think one of the props is not passed in correctly. I sent 25 SMR from the EVM to L1 and I get the following screen on the verification pop-up:

![image](https://github.com/bloomwalletio/bloom/assets/45079109/01df1f61-ed59-499b-8626-9b2b84bcee9d)

![image](https://github.com/bloomwalletio/bloom/assets/45079109/2c8e5acf-61ca-470c-a4b7-8efc436b43af)

Also sometimes the ledger flow errors out with a `No signature provided` message. Maybe this is outside of the scope of this PR. If so, then please create a task :pray: 

Screencast below (relevant part from 0:50-1:15):

[Screencast from 2023-08-30 11:46:01.webm](https://github.com/bloomwalletio/bloom/assets/45079109/4ece73ba-40e1-4fab-99d1-fb4ad56b8bf3)

2023-08-30 09:49 UTC, Tuditi commented on packages/shared/src/lib/core/wallet/actions/send/createEvmChainToEvmChainTransaction.ts
> +    let amount
Missing types

2023-08-30 09:49 UTC, Tuditi commented on packages/shared/src/lib/core/wallet/actions/send/createEvmChainToEvmChainTransaction.ts
> +    let data
missing type

2023-08-30 09:49 UTC, Tuditi commented on packages/shared/src/lib/core/wallet/actions/send/createEvmChainToEvmChainTransaction.ts
> +        // ld the smart contract data,
Maybe move this to one line or fix the break in `bui/ld`.

2023-08-30 09:49 UTC, Tuditi commented on packages/shared/src/lib/core/wallet/actions/send/createEvmChainToStardustNetworkTransaction.ts
> +            return await buildEvmTransactionData(provider, originAddress, ISC_MAGIC_CONTRACT_ADDRESS, '0', data)
I think this throws an error if the user has no base token. It should be caught accordingly so, the non-happy flow is also working well.

2023-08-30 14:39 UTC, maxwellmattryan commented on packages/shared/src/lib/core/layer-2/constants/fallback-estimated-gas.constant.ts
> +    [SendFlowType.TokenUnwrap]: 54800,
This is the number I kept getting in errors from the EVM when I was using `0`, so probably the safest to go with. 
I'm thinking it may be possible to unwrap both SMR/IRC30 tokens at the same time, but not sure how useful this would be.

2023-08-30 14:47 UTC, maxwellmattryan commented on packages/shared/src/lib/core/wallet/actions/send/createEvmChainToStardustNetworkTransaction.ts
> +}
A while back we adopted a rule (can't find it in the handbook) to not write code with an implicit `else` statement, with the main reasoning being it's easier to modify existing code when it's written this way

2023-08-30 14:57 UTC, Tuditi commented on packages/shared/src/lib/core/wallet/actions/send/createEvmChainToStardustNetworkTransaction.ts
> +}
We should rethink that rule. It does look cleaner/more maintainable, if you return automatically from the if statement for type/variable checking.

2023-08-30 21:26 UTC, maxwellmattryan commented
@Tuditi, I think that the incorrect activity behavior is perhaps out of scope of this PR, but I also think the changes Nicole / Mark came up with will fix this.

2023-08-31 12:08 UTC, Tuditi requested changes
Some changes requested, since I cannot unwrap atm due to insufficient gas fee error showing up even if I have sufficient L2 funds.

2023-08-31 12:08 UTC, Tuditi commented on packages/desktop/views/dashboard/send-flow/views/SelectRecipientView.svelte
> +    let networkRecipientError: boolean = false
Change name to `doesNetworkRecipientError` or something similar.
![image](https://github.com/bloomwalletio/bloom/assets/45079109/cbba9943-c3fa-49a0-a92e-17256ec2173f)

2023-08-31 12:08 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/helpers/index.ts
> -export * from './calculateGasFeeInGlow'
These two aren't used outside of the module, so they should be moved back to helpers instead of utils.

2023-08-31 12:08 UTC, Tuditi commented on packages/desktop/views/dashboard/send-flow/views/SelectTokenView.svelte
> +    let tokenError: boolean = false
Same as above

2023-08-31 12:08 UTC, Tuditi commented on packages/desktop/views/dashboard/send-flow/views/TransactionSummaryView.svelte
> +                    preparedOutput
This seems curious. Why would you set the preparedOutput to a previous one if the `createStardustOutputFromSendFlowParameters` function above errors? Maybe the function itself shouldn't contain a try/catch, so that the error is handled on l.57 in this file.

2023-08-31 12:08 UTC, Tuditi commented on packages/shared/src/components/molecules/NetworkRecipientItem.svelte
> +    export let error: boolean = false
Same as above

2023-08-31 12:08 UTC, Tuditi commented on packages/shared/src/components/molecules/NetworkRecipientSelector.svelte
> +    export let error: boolean = false
Same as above.

2023-08-31 12:08 UTC, Tuditi commented on packages/shared/src/components/tiles/TokenAmountTile.svelte
> +    export let error: boolean = false
Same as above.

2023-08-31 12:08 UTC, Tuditi commented on packages/shared/src/lib/core/wallet/actions/send/createEvmChainToEvmChainTransaction.ts
> +        return Promise.resolve(undefined)
Isn't it better to throw errors then to resolve to undefined?

2023-08-31 12:08 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/actions/canAccountMakeEvmTransaction.ts
> +    const baseTokenAmount = getLayer2AccountBalanceForToken(accountIndex, networkId, getCoinType()) ?? 0
This line shows 0 for me even if I have an L2 Balance. I think the issue is `getCoinType`. I logged the balance and the getCoinType() call:
![image](https://github.com/bloomwalletio/bloom/assets/45079109/afdcc1d8-7be4-47e6-9851-015732c059c1)

2023-08-31 12:08 UTC, Tuditi commented on packages/shared/src/lib/core/wallet/actions/send/createEvmChainToStardustNetworkTransaction.ts
> +         * createEvmChainToStardustNetworkTransaction.ts:49 Error: Returned error: request might require more gas than it is allowed by the VM (50000000), or will never succeed
Adjust the comment, since the line + file name can become outdated very quickly.

2023-08-31 14:06 UTC, maxwellmattryan commented on packages/shared/src/lib/core/wallet/actions/send/createEvmChainToStardustNetworkTransaction.ts
> +         * createEvmChainToStardustNetworkTransaction.ts:49 Error: Returned error: request might require more gas than it is allowed by the VM (50000000), or will never succeed
Ah meant to remove this :sweat_smile:

2023-08-31 14:13 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/send-flow/views/TransactionSummaryView.svelte
> +                    preparedOutput
Mmm yeah, it's just existing logic that should be refactored. I'll look at that

2023-08-31 18:40 UTC, maxwellmattryan commented on packages/shared/src/lib/core/layer-2/helpers/index.ts
> -export * from './calculateGasFeeInGlow'
That's not true anymore for `buildAssetAllowance` but I've moved the other back

2023-09-01 09:06 UTC, Tuditi approved these changes
Opened the following tasks while reviewing:

- https://github.com/bloomwalletio/bloom/issues/571
- https://github.com/bloomwalletio/bloom/issues/572
- https://github.com/bloomwalletio/bloom/issues/573
- https://github.com/bloomwalletio/bloom/issues/574

I think they are out of scope for this PR and the functionality works fine!
LGTM! :fire:

2023-09-01 09:19 UTC, merged