feat: connect to dapp via deep link
bloomwalletio/bloom pull request #549
Opened 2023-08-31 13:54 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-09-29 09:44 UTC, Tuditi requested changes
Requested some changes.

2023-09-29 09:44 UTC, Tuditi commented on packages/desktop/views/dashboard/drawers/dapp-config/views/InputConnectionCodeDrawer.svelte
> +    import { validateConnectionCodeUri } from 'shared/src/lib/auxiliary/wallet-connect/utils/validateConnectionCodeUri'
Update the imports so they are from @auxiliary/wallet-connect/utils

2023-09-29 09:44 UTC, Tuditi commented on packages/desktop/views/dashboard/drawers/dapp-config/views/InputConnectionCodeDrawer.svelte
> +        {/if}
Why not test against the error message and show the warning if it equals to the deprecated one? Like that, you can get rid of the additional validation logic, where you sometimes throw an error and in the other time return a boolean.

2023-09-29 09:44 UTC, Tuditi commented on packages/shared/src/lib/auxiliary/deep-link/handlers/dapps/operations/handleDeepLinkAddWCConnectionOperation.ts
> +        }
If checking the error message for the warning, this block could just move into the `validateConnectionCodeUri`.

2023-09-29 09:44 UTC, Tuditi commented on packages/shared/src/lib/auxiliary/wallet-connect/utils/validateConnectionCodeUri.ts
> -        throw Error(localize('error.walletConnect.deprecatedVersion'))
Depending on which locale you go with, either remove this one or remove the new one.

2023-09-29 09:44 UTC, Tuditi commented on packages/shared/src/lib/auxiliary/wallet-connect/actions/pairWithNewDapp.ts
> +        throw err
This error needs to be handled by the app. I have runtime crash at the moment:

![image](https://github.com/bloomwalletio/bloom/assets/45079109/74154b67-f808-49a2-9435-ebb859c09556)

2023-09-29 10:51 UTC, Tuditi commented
Tests and type checking are failing as well.

2023-09-29 11:01 UTC, MarkNerdi commented on packages/shared/src/lib/auxiliary/deep-link/handlers/dapps/operations/handleDeepLinkAddWCConnectionOperation.ts
> +        }
i extracted it from the `validateConnectionCodeUri` function, because on the `InputConnectionDrawer` we handle both validations differently

2023-10-02 06:57 UTC, Tuditi requested changes
I get a runtime error if I paste in the following URL:

wc:fdf08c0a-7e6b-452c-8a67-0bead7610598@2?bridge=https%3A%2F%2Fe.bridge.walletconnect.org&key=401c298de6fea70d25f509651632451b0c04a9d88b88953618c764a08ee5a9cf

![image](https://github.com/bloomwalletio/bloom/assets/45079109/32f514f0-65a5-42d1-90a0-39c97b46ec5d)

2023-10-02 07:06 UTC, Tuditi commented
And another one when connecting to Uniswap:

wc:651daff51ce080a5dbb787451dd04dd75ae1f7d589aaefba84d3646a7272a98e@2?relay-protocol=irn&symKey=6d2ffd64189825dba15aa80842a03dd0fde90805bd4929f73745a61a06559aeb

![image](https://github.com/bloomwalletio/bloom/assets/45079109/a0f2224b-8e2d-4d1a-9f54-fe7bbfea7a75)

2023-10-02 08:08 UTC, Tuditi approved these changes
LGTM! :fire:

2023-10-02 08:11 UTC, merged