chore: redesign `SelectProfileView`
bloomwalletio/bloom pull request #635
Opened 2023-09-07 03:21 UTC by jeeanribeiro

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-09-07 18:37 UTC, maxwellmattryan submitted a review, later dismissed
LGTM :cherry_blossom:

2023-09-07 21:35 UTC, nicole-obrien requested changes
Unable to navigate to the enter pin view

2023-09-07 22:05 UTC, nicole-obrien commented on packages/desktop/views/login/components/ProfileCard.svelte
> +    {#if profile?.name}
Profile should not be empty and neither should name

2023-09-07 22:05 UTC, nicole-obrien commented on packages/desktop/views/login/components/ProfileCard.svelte
> +        <button type="button" class="menu"></button>
can we feature flag this will we add an a menu

2023-09-07 22:05 UTC, nicole-obrien commented on packages/desktop/views/login/components/ProfileCard.svelte
> +            {#if profile?.type === ProfileType.Ledger}
profile should never be empty

2023-09-07 22:05 UTC, nicole-obrien commented on packages/desktop/views/login/components/ProfileCard.svelte
> +        <NetworkBadge size="sm" networkId={profile?.network?.id} networkName={profile?.network?.name} />
not empty profile

2023-09-07 22:05 UTC, nicole-obrien commented on packages/desktop/views/login/components/ProfileCard.svelte
> +        @apply bg-white/0 hover:bg-white/100 focus:bg-white/100;
don't show hover on disabled

2023-09-07 22:05 UTC, nicole-obrien commented on packages/desktop/views/login/components/ProfileCard.svelte
> +    export let updateRequired: boolean = false
not used shouldn't there be an update required badge? Perhaps we need input from ux to show this as a pill

2023-09-08 07:14 UTC, MarkNerdi commented
If i have an NFT as a profile picture, on hover only the background morphs into a square.

![image](https://github.com/bloomwalletio/bloom/assets/37661351/2001e030-1578-420e-8d17-b5c349a1f4c9)
![image](https://github.com/bloomwalletio/bloom/assets/37661351/de3c200d-706a-4963-9f59-beb74941f088)

2023-09-08 07:15 UTC, MarkNerdi commented on packages/desktop/views/login/views/EnterPinView.svelte
> +                <ProfileCard profile={$activeProfile} {updateRequired} />
here this requires a `disable` flag

2023-09-08 18:12 UTC, maxwellmattryan commented on packages/desktop/views/login/views/EnterPinView.svelte
> +                <ProfileCard profile={$activeProfile} {updateRequired} />
Will be fixed in upcoming PR as this technically out of scope of this one

2023-09-08 21:10 UTC, nicole-obrien approved these changes
Approval to get the ball rolling, but we need to make sure we have tasks for:
- Hover affect of avatar
- Avatar shaps in ui kit
- Bloom logos in ui kit
- Background
- Dark mode
- Glass effect of button

2023-09-08 21:30 UTC, merged