feat: choose correct abi to decode evm transactions
bloomwalletio/bloom pull request #687
Opened 2023-09-13 13:17 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-09-13 13:23 UTC, Tuditi commented on packages/shared/src/lib/core/wallet/actions/isAddressATrackedToken.ts
> +export function isAddressATrackedToken(networkId: NetworkId, address: string, profile: IProfile): boolean {
Maybe this sounds better?
```suggestion
export function isTrackedTokenAddress(networkId: NetworkId, address: string, profile: IProfile): boolean {
```

2023-09-13 13:33 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/utils/getTransferInfoFromTransactionData.ts
> +        if (decoded?.name === 'transfer') {
```suggestion
        } else if (decoded?.name === 'transfer') {
```

2023-09-13 13:50 UTC, Tuditi requested changes
Left some comments. I also get an error whenever I try to send fUSDC. Additionaly, the activity is generated twice.

Error:
```
Error: Amount is negative
    at formatTokenAmountDefault (formatTokenAmountDefault.ts:12:1)
    at formatTokenAmountBestMatch (formatTokenAmountBestMatch.ts:27:1)
    at Object.update [as p] (TokenAmountTile.svelte:52:1)
    at update_slot_base (index.mjs:100:1)
    at Object.update [as p] (Text.svelte:176:1)
    at Object.update [as p] (Text.svelte:176:1)
    at update (index.mjs:1298:1)
    at flush (index.mjs:1258:1)
```

Balance change:
![image](https://github.com/bloomwalletio/bloom/assets/45079109/9427c1f5-4591-4392-8b4b-ed71323a127c)

2023-09-13 13:50 UTC, Tuditi commented on packages/shared/src/lib/core/layer-2/utils/getTransferInfoFromTransactionData.ts
Why do you need this function? You're not using it anywhere.

2023-09-13 13:50 UTC, Tuditi commented on packages/shared/src/lib/core/activity/utils/generateActivityFromEvmTransaction.ts
> +        const isErc20 = isAddressATrackedToken(networkId, recipient.address, getActiveProfile())
I would move the call to `getActiveProfile()` into the function. I don't see the added benefit of passing an extra parameter.

2023-09-13 13:50 UTC, Tuditi commented on packages/shared/src/lib/core/activity/utils/generateActivityFromEvmTransaction.ts
> +            if (decoded?.name === 'call') {
Maybe a switch statement works better here?

2023-09-13 14:53 UTC, MarkNerdi commented on packages/shared/src/lib/core/layer-2/utils/getTransferInfoFromTransactionData.ts
i extracted the function into this file. but forgot to use it lol

2023-09-14 07:58 UTC, Tuditi submitted a review, later dismissed
LGTM! :fire:

2023-09-14 09:25 UTC, Tuditi approved these changes

2023-09-14 09:26 UTC, Tuditi approved these changes

2023-09-14 09:30 UTC, merged