ui: fix tabsection height
bloomwalletio/bloom pull request #737
Opened 2023-09-18 15:08 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-09-18 22:15 UTC, nicole-obrien submitted a review, later dismissed
I don't think we should be having random pixel buffers like this? Is there another way around this?

Additionally the dashboard table goes all the way to the bottom in the designs, there is no padding at the bottom of the page.

2023-09-18 22:15 UTC, nicole-obrien commented on packages/desktop/views/dashboard/new-dashboard/NewDashboard.svelte
> +        height: calc(100vh - 39px);
What is this buffer?

2023-09-18 22:15 UTC, nicole-obrien commented on packages/desktop/views/dashboard/new-dashboard/tab-section/activity/ActivityTab.svelte
> +<div class="flex flex-col flex-grow" style="height: calc(100% - 68px);">
What is this buffer?

2023-09-19 06:25 UTC, MarkNerdi commented on packages/desktop/views/dashboard/new-dashboard/tab-section/activity/ActivityTab.svelte
> +<div class="flex flex-col flex-grow" style="height: calc(100% - 68px);">
the header containing the tabs and filter/search

2023-09-19 06:25 UTC, MarkNerdi commented on packages/desktop/views/dashboard/new-dashboard/NewDashboard.svelte
> +        height: calc(100vh - 39px);
top navbar

2023-09-21 13:56 UTC, jeeanribeiro requested changes
[magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) needs to be avoided so we can understand the code

2023-09-21 13:56 UTC, jeeanribeiro commented on packages/desktop/views/dashboard/new-dashboard/tab-section/activity/ActivityTab.svelte
> +<div class="flex flex-col flex-grow" style="height: calc(100% - 68px);">
`68px` is a [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) and it could be avoided by putting it inside a named variable

2023-09-21 13:56 UTC, jeeanribeiro commented on packages/desktop/views/dashboard/new-dashboard/NewDashboard.svelte
> +        height: calc(100vh - 39px);
`39px` is a [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) and it could be avoided by putting it inside a named variable

2023-09-21 14:00 UTC, jeeanribeiro requested changes
The last item in the scrollable activity list is being cut off even when the vertical scroll position is at the end of the scrollbar

![image](https://github.com/bloomwalletio/bloom/assets/42754063/31e794f8-d64c-4aa0-9207-1ea667e0589c)

2023-09-22 12:55 UTC, jeeanribeiro approved these changes

2023-09-22 12:58 UTC, jeeanribeiro approved these changes

2023-09-22 13:27 UTC, jeeanribeiro approved these changes

2023-09-22 13:30 UTC, merged