enhancement: add automatic EVM address generation for Stronghold profiles
bloomwalletio/bloom pull request #744
Opened 2023-09-18 22:22 UTC by maxwellmattryan

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

This improves UX by making the EVM addresses available as soon as possible.

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-09-19 14:56 UTC, MarkNerdi requested changes

2023-09-19 14:56 UTC, MarkNerdi commented on packages/shared/src/lib/core/layer-2/actions/generateAndStoreEvmAddressForAccounts.ts
> +        const accountIndex = account.getMetadata().index
```suggestion
        const accountIndex = account.index
```
although i think we dont need to declare this as a variable

2023-09-19 14:56 UTC, MarkNerdi commented on packages/shared/src/lib/core/profile/actions/active-profile/login.ts
> +            accounts.push(newAccount)
Either
```suggestion
            accounts = [newAccount]
```

or initialize accounts in line 80 with `[ ]`

2023-09-19 14:56 UTC, MarkNerdi commented on packages/shared/src/lib/core/layer-2/actions/generateAndStoreEvmAddressForAccounts.ts
> +    if (accounts.length > 0 && accounts[0].evmAddresses?.[coinType]) {
i think the check `accounts[0].evmAddresses?.[coinType]` should be done inside the for loop for each acccount

2023-09-19 14:56 UTC, MarkNerdi commented on packages/shared/src/lib/core/profile/actions/active-profile/login.ts
> +                void generateAndStoreEvmAddressForAccounts(type, coinType, ...(accounts as IAccountState[]))
not sure if we should do this cast. These accounts are only `IAccount`s, so this could lead to some bugs in the future. Should we maybe rewrite the `getAccounts` and `recoverAccounts` functions such that they return `IAccountState`s?

2023-09-19 14:59 UTC, maxwellmattryan commented on packages/shared/src/lib/core/layer-2/actions/generateAndStoreEvmAddressForAccounts.ts
> +        const accountIndex = account.getMetadata().index
It's best to call the function because when logging I noticed that the non-function properties weren't always there, b/c of the different with `IAccount` and `IAccountState`

2023-09-19 15:00 UTC, maxwellmattryan commented on packages/shared/src/lib/core/layer-2/actions/generateAndStoreEvmAddressForAccounts.ts
> +    if (accounts.length > 0 && accounts[0].evmAddresses?.[coinType]) {
Ah yes, this isn't good logic

2023-09-19 15:01 UTC, maxwellmattryan commented on packages/shared/src/lib/core/profile/actions/active-profile/login.ts
> +                void generateAndStoreEvmAddressForAccounts(type, coinType, ...(accounts as IAccountState[]))
Yeah you're right, I think I may change the signature of `generateAndStoreEvmAddressForAccounts` first

2023-09-19 22:00 UTC, maxwellmattryan commented on packages/shared/src/lib/core/profile/actions/active-profile/login.ts
> +                void generateAndStoreEvmAddressForAccounts(type, coinType, ...(accounts as IAccountState[]))
On second thought, I think it's better to refactor those functions like you mentioned

2023-09-19 22:12 UTC, maxwellmattryan commented on packages/shared/src/lib/core/profile/actions/active-profile/login.ts
> +                void generateAndStoreEvmAddressForAccounts(type, coinType, ...(accounts as IAccountState[]))
I figured out a third options that's pretty easy to change. It might actually be good to keep those functions how they are since they're API wrapper functions, but I can just change `loadAccounts` to return an array of `IAccountState` instead :+1:

2023-09-20 07:25 UTC, MarkNerdi approved these changes
LGTM

2023-09-20 07:28 UTC, MarkNerdi approved these changes

2023-09-20 07:30 UTC, merged