fix: fix account summary reactivity
bloomwalletio/bloom pull request #791
Opened 2023-09-25 09:20 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-09-25 16:52 UTC, Tuditi requested changes
Works well! Requested some minor code changes.

2023-09-25 16:52 UTC, Tuditi commented on packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts
> +            baseCoinTransfer: activity.action !== ActivityAction.Burn ? baseCoinTransfer : undefined,
Maybe this can be moved to line 26, so you don't have these duplications?

2023-09-25 16:52 UTC, Tuditi commented on packages/shared/src/locales/en.json
> +        "smartContract": "Smart Contract"
We already have a locale for smart contract. I think it's okay to use it inside ActivityStatusPills.

2023-09-26 14:32 UTC, MarkNerdi commented on packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts
> +            baseCoinTransfer: activity.action !== ActivityAction.Burn ? baseCoinTransfer : undefined,
fixed in dedicated PR

2023-09-26 16:57 UTC, Tuditi approved these changes
LGTM! :fire:

2023-09-26 17:00 UTC, merged