feat: implement receive flow
bloomwalletio/bloom pull request #816
Opened 2023-09-26 21:02 UTC by maxwellmattryan

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-09-26 21:03 UTC, maxwellmattryan commented
The `qrious` dependency patch was found [here](https://github.com/neocotic/qrious/issues/2).

2023-09-27 07:59 UTC, MarkNerdi requested changes

2023-09-27 07:59 UTC, MarkNerdi commented on packages/desktop/components/popups/ReceiveAddressPopup.svelte
> +            const evmChainNetworkId = selectedNetworkId
i dont think we need this assignment

2023-09-27 07:59 UTC, MarkNerdi commented on packages/desktop/components/popups/ReceiveAddressPopup.svelte
> +            receiveAddress = $selectedAccount.evmAddresses?.[ETHEREUM_COIN_TYPE]
we should use the `chain.getConfiguration().coinType`

2023-09-27 07:59 UTC, MarkNerdi commented on packages/desktop/components/popups/ReceiveAddressPopup.svelte
> +                            ETHEREUM_COIN_TYPE,
also here

2023-09-27 07:59 UTC, MarkNerdi commented on packages/desktop/components/popups/ReceiveAddressPopup.svelte
> +    <Text type="body2" textColor="text-secondary">{localize('popups.receiveAddress.body')}</Text>
```suggestion
    <Text type="body2" textColor="secondary">{localize('popups.receiveAddress.body')}</Text>
```

2023-09-27 07:59 UTC, MarkNerdi commented on packages/desktop/components/popups/ReceiveAddressPopup.svelte
> +    <Text type="h5" textColor="text-brand">{localize('popups.receiveAddress.title')}</Text>
```suggestion
    <Text type="h5" textColor="brand">{localize('popups.receiveAddress.title')}</Text>
```

2023-09-27 07:59 UTC, MarkNerdi commented on packages/desktop/components/popups/ReceiveAddressPopup.svelte
> +            <Text type="h6" textColor="text-brand"
```suggestion
            <Text type="h6" textColor="brand"
```

2023-09-27 07:59 UTC, MarkNerdi commented on packages/desktop/components/popups/ReceiveAddressPopup.svelte
> +            class="w-full py-6 space-y-6 flex flex-col justify-center items-center rounded-xl border border-solid border-stroke bg-surface-1"
also add `dark:border-stroke-dark` and `dark:bg-surface-1-dark`

2023-09-27 07:59 UTC, MarkNerdi commented on packages/shared/src/components/buttons/ReceiveButton.svelte
> +                selectedNetworkId: $network.getMetadata().id,
```suggestion
                selectedNetworkId: getActiveNetworkId(),
```

2023-09-27 07:59 UTC, MarkNerdi commented on packages/shared/src/lib/core/network/utils/getSplitNetworkId.ts
> +    const parts = networkId?.split(':')
if `networkId` can be undefined, pls update the param type. If not, remove the questionmark

2023-09-27 14:18 UTC, maxwellmattryan commented on packages/shared/src/lib/core/network/utils/getSplitNetworkId.ts
> +    const parts = networkId?.split(':')
It's hard because it's not meant to be undefined but it seems that it was passed to this function that way, but I'll try and solve the problem further upstream to prevent it from even being passed in the first place

2023-09-27 15:43 UTC, MarkNerdi approved these changes

2023-09-27 15:49 UTC, merged