chore: cleanup activity list
bloomwalletio/bloom pull request #824
Opened 2023-09-27 14:19 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-09-28 17:04 UTC, Tuditi requested changes
I requested some changes and let's move this into draft mode until we sorted out the height of the search input.

It's too large as discussed on today's stand-up.
![image](https://github.com/bloomwalletio/bloom/assets/45079109/33601c08-48eb-48c2-bd16-383df3cb706b)

2023-09-28 17:04 UTC, Tuditi commented on packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte
> +    import { FontWeight, Illustration, NftGallery, ReceiveButton, Text } from '@ui'
Let's use the bloom-ui Text component

2023-09-28 17:04 UTC, Tuditi commented on packages/desktop/views/dashboard/send-flow/views/components/StardustTransactionDetails.svelte
> +            </div>
What's the benefit of these `div`s?

2023-09-28 17:04 UTC, Tuditi commented on packages/desktop/views/dashboard/send-flow/views/components/StardustTransactionDetails.svelte
> +            </div>
What's the benefit of these `div`s?

2023-09-29 06:34 UTC, MarkNerdi commented on packages/desktop/views/dashboard/send-flow/views/components/StardustTransactionDetails.svelte
> +            </div>
this div ensures that it is sized accordingly

2023-09-29 08:48 UTC, Tuditi approved these changes
LGTM! :fire:

2023-09-29 08:50 UTC, merged