ui: upgrade bloom-ui
bloomwalletio/bloom pull request #862
Opened 2023-09-29 17:46 UTC by nicole-obrien

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-10-01 19:17 UTC, MarkNerdi requested changes

2023-10-01 19:17 UTC, MarkNerdi commented on packages/shared/src/components/inputs/SearchInput.svelte
> +    const searchValue = ''
this needs to be a `let`

2023-10-01 19:17 UTC, MarkNerdi commented on packages/shared/src/components/inputs/SearchInput.svelte
> +<Input bind:value icon={IconName.Search} placeholder={localize('general.search')} />
We need to bind the `bind:value={searchValue}`, because value is only updated via `debounce`

2023-10-01 19:17 UTC, MarkNerdi commented on packages/desktop/views/login/views/SelectProfileView.svelte
>          <button type="button" on:click={onAddProfileClick}>
Is there a reason why the `Button` is wrapped with a `button`?

2023-10-01 22:49 UTC, nicole-obrien commented on packages/desktop/views/login/views/SelectProfileView.svelte
>          <button type="button" on:click={onAddProfileClick}>
The ui requires a the whole container to be clickable, but the text inside is same style as a text button component not sure if this will stay like that 🤷‍♀️

2023-10-02 06:38 UTC, MarkNerdi approved these changes

2023-10-02 06:45 UTC, merged