Feat: connect ledger popups
bloomwalletio/bloom pull request #929
Opened 2023-10-04 19:31 UTC by Tuditi

## Summary

closes: https://github.com/bloomwalletio/bloom/issues/922
closes: https://github.com/bloomwalletio/bloom/issues/999
...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-10-05 06:23 UTC, MarkNerdi commented on packages/desktop/components/popup/popups/ConnectLedgerPopup.svelte
Please use the new `PopupTemplate` for this component :pray:

2023-10-05 06:24 UTC, MarkNerdi commented on packages/desktop/views/dashboard/drawers/network-config/views/ConfirmLedgerEvmAddressDrawer.svelte
> +                <Table orientation="vertical" {items} />
```suggestion
                <Table orientation="vertical" items={
                [
        {
            key: localize('general.evmAddress'),
            value: address,
            copyable: true,
        },
    ]
                 } />
```

2023-10-05 06:24 UTC, MarkNerdi commented on packages/desktop/views/dashboard/drawers/network-config/views/ConfirmLedgerEvmAddressDrawer.svelte
> +    ]
move this into the html part

2023-10-05 08:10 UTC, MarkNerdi submitted a review, later dismissed

2023-10-05 08:10 UTC, nicole-obrien requested changes
I think the ledger SVGs should me transparent and only include the ledger device.
The text should be a pill component 🙏

2023-10-09 11:14 UTC, nicole-obrien commented
Unable to build

2023-10-09 18:27 UTC, nicole-obrien approved these changes

2023-10-09 18:29 UTC, merged